export const baseURL = 'http://localhost:8080/'
export const authenticationServiceURL = baseURL + 'auth/';
export const zuulUserServiceBaseURL = baseURL + 'user-service/user';
export const zuulOrganizationServiceBaseURL = baseURL + 'organization-service/organization';
export const zuulOrganizationEventServiceBaseURL = baseURL + 'organization-service/event';
export const zuulDonationServiceBaseURL = baseURL + 'organization-service/donation';
export const zuulEmployeeServiceBaseURL = baseURL + 'employee-service/employee';
export const zuulEmployeePickupServiceBaseURL = baseURL + 'employee-service/employee/pickup';
export const zuulAdminServiceBaseURL = baseURL + 'admin-service/admin';
export const zuulVolunteerServiceBaseURL = baseURL + 'user-service/volunteer';
